version: '3.5'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/app/dev.Dockerfile
    image: uploadfile-app-service
    restart: always
    working_dir: /app
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql
    networks:
      - uploadfile-network

  nginx:
    image: nginx:1.19.8-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./public:/app/public:cached
      - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:cached
      - ./.docker/app/ssl:/etc/ssl:cached
    ports:
      - 80:80
    networks:
      - uploadfile-network

  mysql:
    image: mysql:5.7.31
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: zcp
      MYSQL_PASSWORD: zcppass
      MYSQL_DATABASE: myproject
    volumes:
      - uploadfile_data:/var/lib/mysql
    networks:
      - uploadfile-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - 8182:80
    networks:
      - uploadfile-network

volumes:
  uploadfile_data:
    driver: local

networks:
  uploadfile-network:
    name: uploadfile-network
    driver: bridge
